# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for f5121 configurations
Name: jolla-configuration-f5121
Requires:
- pattern:jolla-hw-adaptation-f5121
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools
- csd
- sd-utils

Summary: Jolla Configuration f5121

